
services:
  # nginx:
  #   image: nginx:latest
  #   container_name: gateway
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./index.html:/usr/share/nginx/html/index.html:ro
  #   ports:
  #     - "8080:8080" 
  #   networks:
  #     - app-network
  #   depends_on:
  #     - auth-service
  #     - post-service

  auth-service:
    build: ./Backend/auth-service
    container_name: auth-service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - ACCESS_JWT_KEY=dazhbdajbdjadakd
      - REFRESH_TOKEN_SECRET=djendiebdeuibdeuidiue
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./Backend/auth-service/logs:/home/logs/auth-service

  post-service:
    build: ./Backend/post-service
    container_name: post-service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
    restart: unless-stopped
    ports:
      - "3003:3003"
    networks:
      - app-network
    volumes:
      - ./Backend/post-service/logs:/home/logs/post-service

  user-service:
    build: ./Backend/user-service
    container_name: user-service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - MESSAGE_SERVICE_URL=${MESSAGE_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
    restart: unless-stopped
    ports:
      - "3001:3001"
    networks:
      - app-network
    volumes:
      - ./Backend/user-service/logs:/home/logs/user-service

  message-service:
    build: ./Backend/message-service
    container_name: message-service
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - USER_SERVICE_URL=${USER_SERVICE_URL}
      - POST_SERVICE_URL=${POST_SERVICE_URL}
      - NOTIFICATION_SERVICE_URL=${NOTIFICATION_SERVICE_URL}
    restart: unless-stopped
    ports:
      - "3002:3002"
    networks:
      - app-network
    volumes:
      - ./Backend/message-service/logs:/home/logs/message-service

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
